<?php
/** Run with wp eval-file on local. No outgoing mail; QA records moved to Trash. */
if (!defined('WP_CLI') || !WP_CLI || 'local' !== wp_get_environment_type()) throw new RuntimeException('Local CLI only.');
$ids = array();
$assertions = 0;
$check = function ($value, $label) use (&$assertions) { if (!$value) throw new RuntimeException($label); $assertions++; };
$original_settings = get_option('cvipi_contact_notifications');
$user = get_current_user_id();
$mail = array();
$fail_mail = false;
$mock = function ($result, $atts) use (&$mail, &$fail_mail) { $mail[] = $atts; return !$fail_mail; };
add_filter('pre_wp_mail', $mock, 10, 2);
try {
  $config = cvipi_contact_config();
  $form = json_decode(get_post($config['id'])->post_content, true);
  $process = wpforms()->obj('process');
  $data = array('name'=>'CVIPI QA '.wp_generate_uuid4(),'email'=>'qa-'.wp_generate_uuid4().'@example.org','organization'=>'Community QA','role'=>'Coordinator','subject'=>'Contact inbox QA','message'=>"Test message with <script>alert(1)</script> and a backslash \\ preserved.\n\nSecond paragraph.");
  $fields = array();
  foreach ($config['fields'] as $name=>$id) $fields[$id] = array('value'=>$data[$name]);
  $clean = cvipi_contact_fields($fields);
  $check(!is_wp_error($clean) && false === strpos($clean['message'], '<script>'), 'Sanitization');
  $bad = $fields; $bad[$config['fields']['email']]['value'] = "bad@example.org\r\nBcc: other@example.org";
  $check(is_wp_error(cvipi_contact_fields($bad)), 'Header injection rejected');
  $bad = $fields; $bad[$config['fields']['message']]['value'] = str_repeat('a',20001);
  $check(is_wp_error(cvipi_contact_fields($bad)), 'Length bound');
  $process->errors = array($form['id']=>array('recaptcha'=>'Missing CAPTCHA'));
  cvipi_contact_capture($fields, array(), $form);
  $check(empty($GLOBALS['cvipi_contact_saved_id']), 'Invalid submissions not stored');
  $process->errors = array(); $process->spam_reason = 'reCAPTCHA';
  cvipi_contact_capture($fields, array(), $form);
  $check(empty($GLOBALS['cvipi_contact_saved_id']), 'Spam not stored');
  $process->spam_reason = ''; $process->spam_errors = array();
  cvipi_contact_capture($fields, array(), $form);
  $id = $GLOBALS['cvipi_contact_saved_id'] ?? 0; $ids[] = $id;
  $check($id && 'private' === get_post_status($id), 'Saved privately');
  $check(get_post_meta($id,'_cvipi_contact_data',true) === $clean, 'Complete data preserved');
  $check('new' === get_post_meta($id,'_cvipi_contact_state',true), 'New status');
  $check('1' === get_post_meta($id,'_cvipi_contact_unread',true), 'Unread status');
  $check(cvipi_contact_store($clean,$form['id']) === $id, 'Retry deduplicated');
  $check(false === apply_filters('wpforms_entry_email',true,$fields,array(),$form), 'Default contact notification suppressed');
  $check(true === apply_filters('wpforms_entry_email',true,$fields,array(),array('id'=>999999)), 'Other forms unaffected');
  $settings = cvipi_contact_notification_defaults(); $settings['admin_recipients'] = 'team@example.org';
  update_option('cvipi_contact_notifications',$settings);
  cvipi_contact_send_notifications($id);
  $check(count($mail) === 2, 'Exactly two notifications');
  $check(false === strpos($mail[0]['message'],$clean['name']), 'Receipt omits visitor content');
  $check(false !== strpos($mail[1]['message'],'View Message') && false !== strpos($mail[1]['message'],esc_html($clean['email'])), 'Branded team details and link');
  $check(in_array('Reply-To: '.$clean['email'],$mail[1]['headers'],true), 'Team reply goes to submitter');
  $check('accepted' === get_post_meta($id,'_cvipi_notification_admin',true), 'Transport status recorded');
  cvipi_contact_send_notifications($id);
  $check(count($mail) === 2, 'No duplicate notifications');
  $type = get_post_type_object('cvipi_message');
  $check(!$type->public && !$type->publicly_queryable && !$type->show_in_rest && !$type->can_export, 'Private routes and exports');
  wp_set_current_user(0);
  $check(!current_user_can('read_post',$id) && !current_user_can('edit_post',$id), 'Anonymous access blocked');
  $editor = new WP_User(0); $editor->caps = array('editor'=>true); $editor->get_role_caps();
  $check(!$editor->has_cap('read_post',$id) && !$editor->has_cap('edit_post',$id), 'Non-admin access blocked');
  $admin = get_users(array('role'=>'administrator','number'=>1))[0]; wp_set_current_user($admin->ID);
  $check(current_user_can('edit_post',$id), 'Administrator access allowed');
  $check(!current_user_can($type->cap->create_posts), 'Manual creation blocked');
  $_POST = array('cvipi_contact_state'=>'resolved','cvipi_contact_notes'=>'forged');
  do_action('save_post_cvipi_message',$id);
  $check('new' === get_post_meta($id,'_cvipi_contact_state',true), 'Forged save blocked');
  $_POST['cvipi_contact_review_nonce'] = wp_create_nonce('cvipi_contact_review_'.$id);
  $_POST['cvipi_contact_notes'] = wp_slash("Reviewed <script>bad</script> notes \\ here");
  do_action('save_post_cvipi_message',$id);
  $check('resolved' === get_post_meta($id,'_cvipi_contact_state',true), 'Review state saved');
  $check(false === strpos(get_post_meta($id,'_cvipi_contact_notes',true),'<script>'), 'Notes sanitized');
  $check(false !== strpos(get_post_meta($id,'_cvipi_contact_notes',true),'\\'), 'Notes preserve backslashes');
  $check(count($mail) === 2, 'Review sends no email');
  $_POST = array();
  wp_update_post(array('ID'=>$id,'post_status'=>'publish'));
  $check('private' === get_post_status($id), 'Cannot publish message');
  $disabled = $settings; $disabled['admin_enabled']='0'; $disabled['submitter_enabled']='0'; update_option('cvipi_contact_notifications',$disabled);
  $clean['message'] .= ' Disabled'; $id2=cvipi_contact_store($clean,$form['id']); $ids[]=$id2;
  cvipi_contact_send_notifications($id2);
  $check(count($mail) === 2 && 'disabled' === get_post_meta($id2,'_cvipi_notification_admin',true), 'Toggles honored');
  update_option('cvipi_contact_notifications',$settings); $fail_mail=true;
  $clean['message'] .= ' Failed'; $id3=cvipi_contact_store($clean,$form['id']); $ids[]=$id3;
  cvipi_contact_send_notifications($id3);
  $check('failed' === get_post_meta($id3,'_cvipi_notification_admin',true) && get_post($id3), 'Mail failure retains entry');
  $invalid = $settings; $invalid['admin_recipients']='invalid';
  $check(cvipi_contact_sanitize_notifications($invalid) === $settings, 'Invalid recipient setting rejected');
  $html=cvipi_story_email_html('Test','Test','Test',array(),'https://example.org');
  $check(false !== strpos($html,'STORIES FROM THE FIELD') && false !== strpos($html,'Review Story'), 'Story email defaults retained');
  WP_CLI::success($assertions.' Contact inbox checks passed; no mail sent.');
} finally {
  $_POST=array(); wp_set_current_user($user); remove_filter('pre_wp_mail',$mock,10);
  update_option('cvipi_contact_notifications',$original_settings);
  foreach ($ids as $id) if ($id && !is_wp_error($id)) wp_trash_post($id);
}
